### ISSUE TITLE
R_INSTALL_STAGED=FALSE only needed for R (== 3.6.0)

### ISSUE THREAD

**Issue by HenrikBengtsson** [uschpc/documentation-public#5]
A drive-by-comment from the UCSF Wynton HPC Team member here:

In https://github.com/uschpc/documentation-public/blob/master/project_filesystem.md, you write:

> Note: For R version 3.6.0 or greater, if the install fails because of ERROR: moving to final location failed, enter the command Sys.setenv(R_INSTALL_STAGED = FALSE) and try installing again.

We also ran into this bug too when R 3.6.0 came out.  This bug was quickly fixed, meaning, the `R_INSTALL_STAGED=FALSE` workaround is only needed for R 3.6.0, but not in R (>= 3.6.1).  (We set `export R_INSTALL_STAGED=false` systemwide as long as R 3.6.0 is the default on CentOS/EPEL.)

**Comment by drkrynstrng** [comment]
Hi Henrik,

Thanks for pointing this out. I intended to look into this further, but you have saved me the effort. I will change the note.
